name: CppCheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install CppCheck
      run: sudo apt-get install cppcheck

    - name: Run CppCheck on Core Model
      working-directory: model
      run: cppcheck --template='[{file}]:{line}:{severity}:{message}' --suppress="uninitvar:*" .

    - name: Run CppCheck on EnergyPlus Wrapper
      working-directory: energyplus
      run: cppcheck --template='[{file}]:{line}:{severity}:{message}' --suppress="uninitvar:*" .

    - name: Run CppCheck on FMU Wrapper
      working-directory: fmu
      run: cppcheck --template='[{file}]:{line}:{severity}:{message}' --suppress="uninitvar:*" .
