name: Mac Build

on: [push]

jobs:
  mac_release:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: Install System dependencies and LaTeX
      shell: bash
      run: brew install tree

    - name: Create Build Directory
      run: cmake -E make_directory ./build/

    - name: Configure CMake
      working-directory: ./build
      shell: bash
      run: |
        cmake -DCMAKE_BUILD_TYPE:STRING=Release ../

    - name: Build
      working-directory: ./build
      shell: bash
      run: cmake --build . -j 3

    - name: Print Build Tree
      run: tree build/

    - name: Run Unit Tests
      run: build/model_tests

    - name: Run EnergyPlus
      run: build/mock_energyplus

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: MacArtifact
        path: build/mock_energyplus
