name: Windows Releases

on: [push]

jobs:
  windows_release:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Directory
      run: cmake -E make_directory ./build/

    - name: Configure CMake
      working-directory: ./build
      shell: bash
      run: cmake -G "Visual Studio 16 2019" -A x64 ../

    - name: Build
      working-directory: ./build
      shell: bash
      run: cmake --build . -j 2 --config Release

    - name: Run Unit Tests
      run: build/Release/model_tests.exe

    - name: Run EnergyPlus
      run: build/Release/mock_energyplus.exe

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: WindowsArtifact
        path: build/Release/mock_energyplus.exe
